//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTW.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id { get; set; }
        public Nullable<int> modelId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> manufacturerId { get; set; }
    
        public virtual manufacturers manufacturers { get; set; }
        public virtual models models { get; set; }
    }
}
